### ISSUE TITLE
gem、バージョン管理されているEntityを参照している場合、更新時には無効データも含めてloadするようにする

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [dentsusoken/iPLAss#1340]
gem、バージョン管理されているEntityを参照している場合、更新時には無効データも含めてloadするようにする。

現状、
バージョン管理されているEntityを参照している場合、且つ参照先が無効データのみの場合、その参照を解除することが画面上からできない。
更新時には、無効データの参照はnullとしてloadされ、nullと更新しても更新項目に変化ないため、UpdateOptionにて更新対象として認識されない。
（UpdateOption#forceUpdateフラグをONにすることにより、nullに更新可能ではある。ただこの場合、一律にONにしてしまうと意図せず無効データへの参照を解除してしまう可能性がある）

これを、
更新時には、無効データを含めてloadする（LoadOptionにてversionedフラグを有効化）ようにすることにより、画面から無効データの紐づきを明示的に解除できるようにする。

1. 参照元がバージョン管理されている場合
> (1) 検索画面で「すべてのバージョンを検索」で検索している場合
>> - 詳細・編集画面でのLoad時に `versioned` 指定
>> - 更新時のUpdateOptionのTargetVersionとして、`SPECIFIC` を指定
>
> (2) 検索画面で「すべてのバージョンを検索」で検索していない場合（通常検索）
>> - 更新時のUpdateOptionのTargetVersionとして、`CURRENT_VALID` を指定

2. 参照元がバージョン管理されていない場合
> - 検索画面設定に「参照先の保存時バージョンの検索を許可」フラグを追加
> - このフラグがONの場合、検索画面に「保存時のデータを検索」オプションを表示
> 
> (1) 検索画面で「保存時のデータを検索」で検索している場合
>> - 詳細・編集画面でのLoad時に `versioned` 指定
>> - 更新時のUpdateOptionのTargetVersionとして、`SPECIFIC` を指定
>
> (2) 検索画面で「保存時のデータを検索」で検索していない場合（通常検索）
>> - 更新時のUpdateOptionのTargetVersionとして、`CURRENT_VALID` を指定

`EntityManager#update` の差分チェック時の保存済データをLoadする際に、
UpdateOptionのTargetVersionが `SPECIFIC` の場合は、`versioned` 指定する。

**Comment by xkazama-yukio3** [comment]
_(English)_
gem, when referencing a versioned Entity, the load on update will include invalid data.

Currently,
When referencing a versioned Entity and the reference is only to invalid data, the reference cannot be removed from the screen.

When updating, references to invalid data are loaded as `null` , and even if they are updated as `null` , there is no change in the update item, so they are not recognized as an update target in UpdateOption.

(It is possible to update to null by turning on the `UpdateOption#forceUpdate` flag. However, in this case, turning it on uniformly may unintentionally remove references to invalid data.)

This,
When updating, load including invalid data (enable the `LoadOption#versioned` flag), so that the screen can explicitly dereference invalid data.

1. If Entity is version controlled
> (1) When searching with "Find out the version of all" on the search screen
>> - Specify `versioned` in LoadOption when loading on the detail/edit screen.
>> - Specify `SPECIFIC` as the TargetVersion of UpdateOption when updating.
>
> (2) Else (normal search)
>> - Specify `CURRENT_VALID` as the TargetVersion of UpdateOption when updating.

2. Else (Entity is not version controlled)
> - Added `Can retrieval of the version data referenced at the time of saving` flag to SearchView settings
> - If this flag is ON, the "Find out the data at the time of saving" option is displayed on the search screen
>
> (1) When searching with "Find out the data at the time of saving" on the search screen
>> - Specify `versioned` in LoadOption when loading on the detail/edit screen.
>> - Specify `SPECIFIC` as the TargetVersion of UpdateOption when updating.
>
> (2) Else (normal search)
>> - Specify `CURRENT_VALID` as the TargetVersion of UpdateOption when updating.

When loading saved data at the time of difference check of `EntityManager#update`, 
If the TargetVersion of UpdateOption is `SPECIFIC`, specify `versioned` in LoadOption.

**Comment by xkazama-yukio3** [comment]
**Compatibility notes**
今回の修正により、バージョン管理されているEntityの更新時の処理が変更されます。

EntityManager#updateに指定するUpdateOptionのTargetVersionで `SPECIFIC` を指定している場合、
更新データの差分チェック時に、今までは指定されている `oid` `version` の最新データとの比較を行っていましたが、
今回から指定されている `oid` `version` の保存時のデータとの比較を行い、更新対象プロパティを判断します。

具体的に影響があるのは、以下のパターンです。
- 参照元のEntityがバージョン管理されている
- 参照プロパティとして、バージョン管理されている参照先のバージョンタイプが `最新バージョンを取得` となっているプロパティをもつ

この場合に、
- 参照元Entityの登録画面で参照先（①）を選択して保存する
- 参照先Entityの登録画面で参照先の新しいバージョン（②）を作成する
- 参照元EntityのCSVダウンロードで「全てのバージョンを検索」を指定せずにダウンロードする（最新の②が取得される）
- （CSVダウンロードで「全てのバージョンを検索」を指定した場合は保存時のバージョン（①）が取得されます）
- このファイルをそのままCSVアップロードする

今までは参照先に変更は発生しませんが、今回から変更が発生します（①が②になります）

対象機能は以下です。
- [gemのCSVアップロード機能](https://iplass.org/docs/developerguide/genericentitymanager/entityview/index.html#_csv%E3%82%A2%E3%83%83%E3%83%97%E3%83%AD%E3%83%BC%E3%83%89%E7%94%BB%E9%9D%A2)
- [Entity CRUD APIのCSVアップロード機能](https://iplass.org/docs/developerguide/webapi/index.html#_csv%E3%82%A2%E3%83%83%E3%83%97%E3%83%AD%E3%83%BC%E3%83%89)
- カスタマイズ機能として、EntityManager#updateにTargetVersionで `SPECIFIC` を指定している機能

次回のリリースにて、互換性維持のためのフラグを提供する予定です。
上記の変更が影響ある場合は、次回以降のバージョンを利用してください。

**Comment by xkazama-yukio3** [comment]
_(English)_
### Compatibility notes
This fix changes the process when updating a version-controlled Entity.

When `SPECIFIC` is specified in TargetVersion of UpdateOption specified for EntityManager#update,
When checking for differences in updated data, the latest data of the specified `oid` `version` was compared until now,
From now on, the data at the time of saving of the specified `oid` `version` will be compared to determine the properties to be updated.

This will change the behavior of the CSV upload process for version-controlled Entity.

**Affected features**

- [CSV upload function of gem](https://iplass.org/docs/developerguide/genericentitymanager/entityview/index.html#_csv%E3%82%A2%E3%83%83%E3%83%97%E3%83%AD%E3%83%BC%E3%83%89%E7%94%BB%E9%9D%A2)
- [CSV upload function of Entity CRUD API](https://iplass.org/docs/developerguide/webapi/index.html#_csv%E3%82%A2%E3%83%83%E3%83%97%E3%83%AD%E3%83%BC%E3%83%89)

The situations in which the behavior changes are as follows.

As an Entitiy definition,
- The root Entity is version controlled.
- The reference property has a reference to a version controlled destination.
- The version type of the reference property is `Latest version gets`.

Perform the following operations
- On the registration screen of the reference source Entity, select the reference entity (v1) and save it.
- Register a new version of the referenced entity (v2) on the registration screen of the referenced entity
- Download the CSV download of the referring Entity without specifying "Find out the version of all" 
(the latest version (v2) is acquired)
- (If "Find out the version of all" is specified in the CSV download, the version at the time of saving (v1) will be obtained.)
- CSV upload this file as it is.

The reference entity has not been changed so far, but it will be changed from this time (v1 will be changed to v2).

In addition, 
the customization logic that specifies `SPECIFIC` in TargetVersion for EntityManager#update is also affected in the same way by this modification.
This modification will have the same effect (the data may be updated unintentionally due to a change in the value of the Entity data to be checked for differences).

We will provide flags to maintain compatibility in the next release.
If the above changes affect you, please use the next version or later.

**Improvements in this version**
- When searching with "Find out the version of all", the search result shows the data at the time of saving 
(even if the type is `Latest version gets`), 
but when the detail/edit screen is displayed, the latest data (depending on the type) is displayed.
- When CSV downloaded by specifying "Find out the version of all" was uploaded as is, until now, changes were occurring 
(v2 became v1).
