### ISSUE TITLE
Entityデータのupdate時の更新対象判定時にNormalizer設定を適用する

### ISSUE THREAD

**Issue by xkazama-yukio3** [dentsusoken/iPLAss#1370]
Entityデータのupdate処理において、
更新対象プロパティの判定時にNormalizer設定を適用した状態で判定するように改善する。

現状、

- Validation実行時は、Normalizerが適用された値と登録済データの比較
- Validation未実行時は、Normalizerが適用されない値と登録済データの比較

となっているので、Normalizerを適用した値との比較に合わせる。

**Comment by HiguchiKiyoshi** [comment]
_(English)_
In the update process of entity data, improve the judgment of properties to be updated so that the Normalizer setting is applied when judging the properties to be updated.

Current status,

- When Validation is performed, the value to which the Normalizer is applied is compared with the registered data.
- When Validation is not performed, values to which the Normalizer is not applied are compared with the registered data.

The comparison is made with the value to which the Normalizer is applied.
