### ISSUE TITLE
Entity CRUD WebAPI、csv形式で結果取得の際にfooter行を出力可能に

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [dentsusoken/iPLAss#1519]
### 概要

Entity CRUD WebAPI、csv形式で結果取得の際にfooter行を出力可能にする。
検索処理のタイムアウトで切断された場合など予期せぬ例外時に、csvの場合は出力が途中で切れてしまう。
最後まで正常にデータ取得完了したかどうかの判別ができない。

gemのCSVダウンロード機能同様にfooter行の出力を可能とする。
WebAPIリクエスト時のqueryパラメータにて、footer=trueが指定された場合は、あらかじめ設定ファイルにて定義してある固定のfooter文字列をcsv最終行に出力するようにする。

**Comment by xnie-yabin2** [comment]
_(English)_

### Overview
Enable the output of a footer row when obtaining results in CSV format from the Entity CRUD WebAPI.

In cases of unexpected exceptions, such as when a search operation is interrupted due to a timeout, the CSV output may be truncated. This makes it impossible to determine whether the data retrieval was completed successfully.

Similar to the CSV download feature in the gem, we want to enable the output of a footer row. When the query parameter footer=true is specified in the WebAPI request, the system should output a fixed footer string defined in the configuration file as the last row of the CSV.
