### ISSUE TITLE
GEM:ファイルアップロード失敗時にエラーメッセージが表示されずスピナーアイコンが表示されたままになる

### ISSUE THREAD

**Issue by HiguchiKiyoshi** [dentsusoken/iPLAss#1645]
### 概要

GEMのファイルアップロードにおいて、ファイルアップロード失敗時（ウイルススキャンなどにより）に、エラーメッセージが表示されずスピナーアイコンが表示されたままになる。

### 再現手順

1. FileScannerの実装にて例外を発生させるような状況にする
2. GEMのEntityの更新画面よりファイルアップロードする

**Comment by xkazama-yukio3** [comment]
_(English)_

### Overview
In GEM file upload, when file upload fails (due to virus scan, etc.), the spinner icon remains displayed without error message.

### Steps to Reproduce
1. Create a situation in the FileScanner implementation that raises an exception.
2. Upload the file from the GEM Entity Update screen.
